version: 0.2

phases:
  install:
    commands:
      - echo Installing httpd
      - sudo yum update -y
      - sudo yum install httpd -y
      - sudo systemctl enable httpd
  build:
    commands:
      - echo Build started on `date`
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
